### PR TITLE
Add Website

### LINKED ISSUE #12: Add a website
I just need a HTML type website, hosted on Heroku.

- Sign up in an [Heroku](https://id.heroku.com/login) account.
- Deploy the website.
- Take credentials from me.
- Deploy on my Heroku account.

### PR DESCRIPTION
**Pull request by mridubhatnagar**
Fix <https://github.com/tapaswenipathak/Women-Communities/issues/12>

### CODE REVIEW

**Review by tapaswenipathak — COMMENTED** [review]
Please put screenshot or herokuapp link.

**Comment by mridubhatnagar** [comment]
Screenshot from 2019-05-04 13-11-25

**Comment by mridubhatnagar** [comment]
This is on my local. Yet to be deployed.

**Review by tapaswenipathak — CHANGES_REQUESTED** [review]
Whenever you create a website see if you have -

- `<!DOCTYPE html>`
- `<html lang="lang_val">`
- `<head>`
- `<title>`
- `<meta charset="charset_type">`
- `<meta name = "keywords" />` HTML tag
- `<meta name = "description"` HTML tag.
-  `<meta name = "author">` You can add your name.
- ` <meta http-equiv` `text/html`. 

Deploy on Heroku app, I will merge. You can read online what are these HTML fields.

Then you can say **done**. :)

**Comment by mridubhatnagar** [comment]
Before merge should I deploy?
Your credentials or should I login using the account I made.

**Comment by tapaswenipathak** [comment]
A heroku app deployed w/ the code you wrote would do.

**Comment by mridubhatnagar** [comment]
yes. This is my first deployment. :)
https://communities-for-women.herokuapp.com/

**Comment by tapaswenipathak** [comment]
Great! Can you add the heroku files?

Delete the women communities present in the PR.

**Comment by mridubhatnagar** [comment]
Yes, sure. I'll push here.

**Review by tapaswenipathak — COMMENTED** [review]
I have created a deployment, from discussion from chat, you need a upstream/rebase. I am excited seeing this deployed.

**Comment by mridubhatnagar** [comment]
Screenshot from 2019-05-04 22-04-05

**Comment by tapaswenipathak** [comment]
Post these

- `git log`
- `git log --pretty=short`
- `git reflog`
- `git rebase -i <gitsha>` - `gitsha` value?

Let me see.

**Comment by tapaswenipathak** [comment]
I fixed, merging.

**Comment by mridubhatnagar** [comment]
1. Git log 
Screenshot from 2019-05-04 22-24-13

2. git log --pretty=short
Screenshot from 2019-05-04 22-25-14

3. git reflog
Screenshot from 2019-05-04 22-26-58


4. git rebase --i gitsha
Screenshot from 2019-05-04 22-35-23

**Comment by tapaswenipathak** [comment]
Few things - 

- Whenever you work w/ git make sure every issue/work has separate branch. Now you have 
  `git checkout -b add-website` from the branch you PRed adding names of the communities. So the `add-website` branch is keeping those commits.

- rebase command is `git rebase -i <gitsha>`, you are doing `git rebase --i <gitsha>` so the command errors.

- While `git rebase -i <gitsha>` you can just `drop` commits. 

- You are doing `git rebase -i master`, you should add a `gitsha` so the command errors.

You were great, this happens.

**Comment by prondubuisi** [comment]
Hello @mridubhatnagar Good work. You Rock!

**Comment by prondubuisi** [comment]
So am wondering @mridubhatnagar does this deploy automatically? If we add more women community links will the change be reflected on heroku? also do I need to make changes to both the readme and html files to make changes reflect on the website?

**Pull request merged**
