### PR TITLE
Generic communities

### PR DESCRIPTION
**Pull request by mridubhatnagar**
ref #18.

### CODE REVIEW

**Review by tapaswenipathak — COMMENTED** [review]
Please delete `List of generic communities for women` line and squash the commits.

**Comment by mridubhatnagar** [comment]
Working on this.

**Comment by mridubhatnagar** [comment]
Done.

**Review by tapaswenipathak — COMMENTED** [review]
Superb! There is an extra line, please delete the line and I will merge. :)

**Comment by mridubhatnagar** [comment]
> Superb! There is an extra line, please delete the line and I will merge. :)

Updated.

**Pull request merged**
